# Generated by Django 5.2.5 on 2025-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Agent', 'Agent'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
