# Generated by Django 5.2.5 on 2025-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('agent', 'Agent'), ('admin', 'Admin')], max_length=10),
        ),
    ]
