# Generated by Django 5.2.5 on 2025-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_property_type'),
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_properties',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='properties.property'),
        ),
    ]
