# Generated by Django 5.2.5 on 2025-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_owner_property_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='dealer',
        ),
        migrations.AddField(
            model_name='property',
            name='dealer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
