# Generated by Django 5.2.5 on 2025-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_dealer_id_property_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Room', 'Room'), ('House', 'House'), ('Flat', 'Flat'), ('Portion', 'Portion')], max_length=20),
        ),
    ]
